version: "3.8"

services:
  mysql-dev:
    image: mysql:8.3
    container_name: mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mart
    ports:
      - "3306:3306"
    networks:
      - ninteenmart

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mart2
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - ninteenmart
    expose:
      - 9000
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql-dev
      DB_PORT: 3306
      DB_DATABASE: mart
      DB_USERNAME: root
      DB_PASSWORD: root

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ninteenmart

networks:
  ninteenmart:
